create database DeTodoUnPoco;
use DeTodoUnPoco;


CREATE TABLE EMPLEADOS (
    -- identificadores
    ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD NVARCHAR(100) NOT NULL,
    token_sesion VARCHAR(255) DEFAULT NULL,
    
    -- detalle
    ROL VARCHAR(100) NOT NULL,
    IMAGEN VARCHAR(255)
);

CREATE TABLE CLIENTES (
    -- identificadores
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD NVARCHAR(100) NOT NULL,
    token_sesion VARCHAR(255) DEFAULT NULL,
    IMAGEN VARCHAR(255)
);


CREATE TABLE PLATILLOS (
    -- identificadores
    ID_PLATILLO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    
    -- detalles del platillo
    PRECIO DECIMAL(10,2) NOT NULL,
    DISPONIBLE BOOLEAN DEFAULT TRUE,
    DESCRIPCION TEXT,
    IMAGEN VARCHAR(255),
    CATEGORIA VARCHAR(50)
);


CREATE TABLE PEDIDOS (
    -- Identificadores
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    FECHA_COMPRA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Tabla de detalles del pedido
    ID_PLATILLO INT,
    CANTIDAD INT,
    TOTAL DECIMAL(10,2),
    ESTADO ENUM('prep', 'ready', 'done') DEFAULT 'prep',
    
    -- llaves
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLOS(ID_PLATILLO),
    FOREIGN KEY (ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
);


CREATE TABLE RESEÑAS (
    -- identificador
    ID_RESEÑA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PLATILLO INT,

    -- detalles
    ID_USUARIO INT NULL,
    CALIFICACION INT CHECK (calificacion BETWEEN 1 AND 5),
    COMENTARIOS TEXT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- llaves
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLOS(ID_PLATILLO),
    FOREIGN KEY (ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
);

-- insertar platillos iniciales
INSERT INTO PLATILLOS (NOMBRE, PRECIO, DISPONIBLE, DESCRIPCION, IMAGEN, CATEGORIA) VALUES
('Tacos al pastor', 25, TRUE, 'Con piña y salsa verde', 'imagenes/3-tacos-al-pastor.jpeg', 'Tacos'),
('Hamburguesa clásica', 89, TRUE, 'Carne 150g, queso, jitomate', 'imagenes/hamburguesa-clasica.jpg', 'Hamburguesa'),
('Agua de horchata', 25, TRUE, '500 ml', 'imagenes/Agua_de_horchata.jpg', 'Bebida');

-- inserta usuarios iniciales
INSERT INTO EMPLEADOS 	(NOMBRE, EMAIL ,PASSWORD,ROL) VALUES ('Luis','LuisEnrique@gmail.com', 'Le982895544','Administrador');
INSERT INTO EMPLEADOS 	(NOMBRE, EMAIL ,PASSWORD,ROL) VALUES ('Angel','PerezAngel@gmail.com', 'Pa123456789','Vendedor');
INSERT INTO CLIENTES	(NOMBRE, EMAIL ,PASSWORD) VALUES ('Juan','JuanBautista@gmail.com', 'Jb987654321');

ALTER TABLE CLIENTES ADD COLUMN token_sesion VARCHAR(255) DEFAULT NULL;
ALTER TABLE CLIENTES ADD COLUMN PASSWORD NVARCHAR(100) NOT NULL;


ALTER TABLE CLIENTES ADD COLUMN IMAGEN VARCHAR(255); 
ALTER TABLE EMPLEADOS ADD COLUMN IMAGEN VARCHAR(255);


-- ver tablas
SELECT * FROM CLIENTES; 
SELECT * FROM EMPLEADOS;
SELECT * FROM PLATILLOS;
SELECT * FROM PEDIDOS;
SELECT * FROM RESEÑAS;

-- eliminar 
DROP TABLE CLIENTES;
DROP TABLE EMPLEADOS;
DROP TABLE PLATILLOS;
DROP TABLE PEDIDOS;
DROP TABLE RESEÑAS;


-- actualizar
UPDATE PLATILLOS SET CATEGORIA = 'Tostadas' WHERE ID_PLATILLO = 6;

ALTER TABLE RESEÑAS MODIFY ID_USUARIO INT NULL;

