create database DeTodoUnPoco;
use DeTodoUnPoco;


CREATE TABLE CUENTAS (
    -- identificadores
    ID_CUENTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD NVARCHAR(100) NOT NULL,
    token_sesion VARCHAR(255),
    -- detalle
    ROL ENUM('Invitado','Cliente','Vendedor','Administrador') NOT NULL DEFAULT 'Cliente',
    IMAGEN VARCHAR(255)
);

CREATE TABLE PLATILLOS (
    -- identificadores
    ID_PLATILLO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    
    -- detalles del platillo
    PRECIO DECIMAL(10,2) NOT NULL,
    DISPONIBLE BOOLEAN DEFAULT TRUE,
    DESCRIPCION TEXT,
    IMAGEN VARCHAR(255),
    CATEGORIA VARCHAR(50)
);

CREATE TABLE PEDIDOS (
    -- Identificadores
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CUENTA INT,
    FECHA_COMPRA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Tabla de detalles del pedido
    ID_PLATILLO INT,
    CANTIDAD INT,
    TOTAL DECIMAL(10,2),
    ESTADO ENUM('prep', 'ready', 'done') DEFAULT 'prep',
    
    -- llaves
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLOS(ID_PLATILLO),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTAS(ID_CUENTA)
);


CREATE TABLE RESEÑAS (
    -- identificador
    ID_RESEÑA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PLATILLO INT,

    -- detalles
    ID_CUENTA INT NULL,
    CALIFICACION INT CHECK (calificacion BETWEEN 1 AND 5),
    COMENTARIOS TEXT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- llaves
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLOS(ID_PLATILLO),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTAS(ID_CUENTA)
);
