CREATE DEFINER=`root`@`localhost` PROCEDURE `new_procedure`()
BEGIN

CREATE TABLE EMPLEADOS (
    -- identificadores
    ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD NVARCHAR(100) NOT NULL,
    
    -- detalle
    ROL VARCHAR(100) NOT NULL
);

CREATE TABLE CLIENTES (
    -- identificadores
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL
);


CREATE TABLE PLATILLOS (
    -- identificadores
    ID_PLATILLO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    
    -- detalles del platillo
    ID_EMPLEADO INT, 
    PRECIO DECIMAL(10,2) NOT NULL,
    DISPONIBLE BOOLEAN DEFAULT TRUE,
    DESCRIPCION TEXT,
    IMAGEN VARCHAR(255),
    CATEGORIA VARCHAR(50),
    
    -- llave
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);


CREATE TABLE PEDIDOS (
    -- Identificadores
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    FECHA_COMPRA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Tabla de detalles del pedido
    ID_PLATILLO INT,
    CANTIDAD INT,
    TOTAL DECIMAL(10,2),
    ESTADO ENUM('prep', 'ready', 'done') DEFAULT 'prep',
    
    -- llaves
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLOS(ID_PLATILLO),
    FOREIGN KEY (ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
);


CREATE TABLE RESEÑAS (
    -- identificador
    ID_RESEÑA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PLATILLO INT,

    -- detalles
    ID_USUARIO INT,
    CALIFICACION INT CHECK (calificacion BETWEEN 1 AND 5),
    COMENTARIOS TEXT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- llaves
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLOS(ID_PLATILLO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

END